version: '3.3'

services:
   db:
     image: mariadb:latest
     volumes:
       - db_data:/var/lib/mysql
       - "./docker/sql:/sql:ro" # share import dir /sql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: drupal
       MYSQL_DATABASE: drupal
       MYSQL_USER: drupal
       MYSQL_PASSWORD: drupal

   drupal: #https://hub.docker.com/_/drupal/
     depends_on:
       - db
     image: drupal:composer
     # build: .
     ports:
       - "80"
     restart: always
     volumes:
        - ./docker/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini:ro
        - ./docker/apache2/000-default.conf:/etc/apache2/sites-enabled/000-default.conf # change /var/www/html => /var/www/drupal/web
        - drupal_config:/var/www/drupal/config
        - drupal_files:/var/www/drupal/web/sites/default/files
        - ./drupal/modules/custom:/var/www/drupal/web/modules/custom
        - ./drupal/themes/custom:/var/www/drupal/web/themes/custom
        # - ./wp-content:/var/www/html/wp-content
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: drupal
       WORDPRESS_DB_PASSWORD: drupal

volumes:
    db_data:
    drupal_files:
    drupal_config: