version: '3.3'

services:
   db:
     image: mariadb:latest
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     network_mode: "bridge"
     environment:
       MYSQL_ROOT_PASSWORD: drupal
       MYSQL_DATABASE: drupal
       MYSQL_USER: drupal
       MYSQL_PASSWORD: drupal

   drupal:
     depends_on:
       - db
     build: .
     # ports:
     #   - "9410:80"
     # image: guoxiangke/dcdc_opigno
     links:
        - db:mysql
     restart: always
     network_mode: "bridge"
     volumes:
        - ./docker/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini:ro
        # change /var/www/html => /var/www/drupal/html
        - ./docker/apache2/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
        - drupal_config:/var/www/drupal/config
        - drupal_files:/var/www/drupal/html/sites/default/files
        - ./drupal/modules/custom:/var/www/drupal/html/modules/custom
        - ./drupal/themes/custom:/var/www/drupal/html/themes/custom     
     environment:
        - VIRTUAL_HOST=jobforchina.com
        - LETSENCRYPT_HOST=jobforchina.com
        - LETSENCRYPT_EMAIL=dale.tel@139.com

volumes:
    db_data:
    drupal_files:
    drupal_config:
